services:
  simulador-can:
    build: .
    image: test-vhal-automotive:latest
    container_name: simulador_vhal_automotive
    environment:
      - ADB_SERVER_SOCKET=tcp:host.docker.internal:5037
    network_mode: "host"
    command: python -m unittest 10_Vehicle_Network_Internet/test_network.py
